apiVersion: v1
kind: Pod
metadata:
 name: nodehelloworld.example.com
 labels:
   app: helloworld
spec:
 containers:
   - name: node-demo
     image: abhishek4794/nodejsapp:v1
     ports:
     - name: nodejs-port
       containerPort: 4794
