apiVersion: v1
kind: ReplicationController
metadata : 
 name: helloworld-container 
spec :
 replicas: 2
 selector:
  app: helloworld
 template:
  metadata:
   labels:
    app: helloworld
  spec:
   containers:
   - name: node-demo
     image: abhishek4794/nodejsapp:v1
     ports:
     - containerPort: 4794
