kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  type : NodePort
  ports:
  - protocol: TCP
    port: 31001
    nodePort: 31001
    targetPort: nodejs-port
