
apiVersion: v1
kind: Pod
metadata:
  name: database-redis
  labels:
    app: database-redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - name: redis-port
      containerPort: 6379
